### ISSUE TITLE
when is the code available?

### ISSUE THREAD

**Issue by wolf943134497** [wwenhongich/LIO-FUSION#1]
Hi @wwenhongich  
Thanks your great works!
when is the code available?
Thanks!

**Comment by DreamWaterFound** [comment]
+1

**Comment by ZOUJIASHUAI** [comment]
+2

**Comment by Aviana-Zheng** [comment]
+3

**Comment by snakehaihai** [comment]
+10086

**Comment by tlgkyn06** [comment]
+5

**Comment by Griwa88** [comment]
+6

**Comment by YangSiri** [comment]
Hi, @wwenhongich 

Congratulations on your accepted paper! Looking forward to your codes!

**Comment by ye-tingfeng** [comment]
+7
cy

**Comment by Aokiji996** [comment]
+10

**Comment by whw-create** [comment]
看来开不了了~~~

**Comment by snakehaihai** [comment]
> 看来开不了了~~~

发个邮件去RAL编辑部问问

**Comment by whw-create** [comment]
> > 看来开不了了~~~
> 
> 发个邮件去RAL编辑部问问

这个只看作者想不想开源吧，跟编辑部应该没什么关系

**Comment by snakehaihai** [comment]
> > > 看来开不了了~~~
> > 
> > 
> > 发个邮件去RAL编辑部问问
> 
> 这个只看作者想不想开源吧，跟编辑部应该没什么关系

也是 他们没说开源是contribution 可以不发。 那的确可以取关了

**Comment by dxdydz3dt** [comment]
Codes?

**Comment by thisparticle** [comment]
codes?

**Comment by defe41251135** [comment]
+N

**Comment by robot-mh** [comment]
+inf
