### ISSUE TITLE
Missing reference in paper

### ISSUE THREAD

**Issue by contagon** [wwenhongich/LIO-FUSION#4]
Hey,

First off, thank you for sharing your excellent work. I look forward to the code release.

I was reading through the LIO-Fusion paper and was interested in more details on the wheel encoder factors, referenced as coming from [19]. Unfortunately, reference 19 is the following:

> D. Wu, X. Zhong, X. Peng, H. Hu, and Q. Liu, “iSAM2: Incremental smoothing and mapping using the Bayes tree,” IEEE Trans. Instrum. Meas, vol. 71, pp. 1–15, 2022.

which I believe is an incorrect title. Would you mind pointing me to the correct reference here?

Best, Easton

**Comment by wwenhongich** [comment]
Thanks for pointing out the incorrect title of [19] in our paper. In fact, we have contacted the editors for a correction. 
The correct reference 19 is as follows:
>[19] D. Wu, X. Zhong, X. Peng, H. Hu, and Q. Liu, “Multimodal information fusion for high-robustness and low-drift state estimation of ugvs in diverse scenes,” IEEE Trans. Instrum. Meas, vol. 71, pp. 1–15, 2022.

**Comment by contagon** [comment]
Perfect, thanks for the quick response.
